sudo: required
dist: trusty
language: ruby
rvm:
  - jruby-9.0.1.0
notifications:
  email: false
script: xvfb-run bundle exec rake
env:
  global:
    - BUNDLE_JOBS=4
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    - "JRUBY_OPTS='--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Xss2m -Xcompile.invokedynamic=false'"

addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
gemfile:
  - gemfiles/2.7.gemfile
before_install:
  - gem install bundler
install: bundle
